/**
 * Seed data for the Membership Plans module.
 *
 * Values mirror the Super Admin Portal reference (the 5 network plans). Used as
 * a fallback until the backend plan-template endpoints are live — the request
 * shape in usePlans already matches the intended API.
 */
import { PLAN_COLORS } from '../centres/constants';

import type { GuestChargeDefaults, MembershipPlan } from './types';

export const SEED_PLANS: MembershipPlan[] = [
  {
    id: 'premium',
    name: 'Premium',
    code: 'premium',
    description: 'Full 24/7 access with the highest fortnightly slot allowance.',
    colour: PLAN_COLORS.premium,
    fortnightlyPrice: 59.95,
    annualPrice: 2493.92,
    accessType: '24/7',
    accessHours: '24/7',
    peakAccess: true,
    slotsPerCycle: 7,
    dailyBookingLimit: 1,
    maxFutureBookings: 2,
    carryover: 2,
    carryCap: 4,
    advanceWindowDays: 7,
    extraSessionEnabled: true,
    extraSessionPrice: 30,
    eligibility: { adult: true, junior: false, family: false },
    additionalMemberFee: null,
    memberCap: 0,
    centresActive: 5,
    regions: ['all'],
    status: 'active',
  },
  {
    id: 'standard',
    name: 'Standard',
    code: 'standard',
    description: 'All-hours access with a moderate fortnightly slot allowance.',
    colour: PLAN_COLORS.standard,
    fortnightlyPrice: 39.95,
    annualPrice: 1661.92,
    accessType: '24/7',
    accessHours: '24/7',
    peakAccess: true,
    slotsPerCycle: 3,
    dailyBookingLimit: 1,
    maxFutureBookings: 2,
    carryover: 2,
    carryCap: 2,
    advanceWindowDays: 7,
    extraSessionEnabled: true,
    extraSessionPrice: 30,
    eligibility: { adult: true, junior: true, family: false },
    additionalMemberFee: null,
    memberCap: 0,
    centresActive: 5,
    regions: ['all'],
    status: 'active',
  },
  {
    id: 'offpeak',
    name: 'Off Peak',
    code: 'offpeak',
    description: 'Discounted access during off-peak windows with unlimited off-peak slots.',
    colour: PLAN_COLORS.offpeak,
    fortnightlyPrice: 19.95,
    annualPrice: 829.92,
    accessType: 'offpeak',
    accessHours: '9am–3pm Mon–Fri & 11pm–6am Mon–Sun',
    peakAccess: false,
    slotsPerCycle: 0,
    dailyBookingLimit: 1,
    maxFutureBookings: 2,
    carryover: 0,
    carryCap: 0,
    advanceWindowDays: 7,
    extraSessionEnabled: false,
    extraSessionPrice: 0,
    eligibility: { adult: true, junior: false, family: false },
    additionalMemberFee: null,
    memberCap: 0,
    centresActive: 5,
    regions: ['all'],
    status: 'active',
  },
  {
    id: 'nightowl',
    name: 'Night Owl',
    code: 'nightowl',
    description: 'Late-night access (11pm–6am) with unlimited overnight slots.',
    colour: PLAN_COLORS.nightowl,
    fortnightlyPrice: 13.95,
    annualPrice: 580.32,
    accessType: 'nightowl',
    accessHours: '11pm–6am only',
    peakAccess: false,
    slotsPerCycle: 0,
    dailyBookingLimit: 1,
    maxFutureBookings: 2,
    carryover: 0,
    carryCap: 0,
    advanceWindowDays: 7,
    extraSessionEnabled: false,
    extraSessionPrice: 0,
    eligibility: { adult: true, junior: false, family: false },
    additionalMemberFee: null,
    memberCap: 0,
    centresActive: 5,
    regions: ['all'],
    status: 'active',
  },
  {
    id: 'family',
    name: 'Family',
    code: 'family',
    description: 'Shared family membership with full access and per-member add-ons.',
    colour: PLAN_COLORS.family,
    fortnightlyPrice: 39.95,
    annualPrice: 1661.92,
    accessType: '24/7',
    accessHours: '24/7',
    peakAccess: true,
    slotsPerCycle: 3,
    dailyBookingLimit: 1,
    maxFutureBookings: 2,
    carryover: 2,
    carryCap: 2,
    advanceWindowDays: 7,
    extraSessionEnabled: true,
    extraSessionPrice: 30,
    eligibility: { adult: true, junior: true, family: true },
    additionalMemberFee: 10,
    memberCap: 0,
    centresActive: 5,
    regions: ['all'],
    status: 'active',
  },
];

export const SEED_GUEST_DEFAULTS: GuestChargeDefaults = {
  firstGuestFee: 30,
  additionalGuestDiscountPct: 20,
  maxGuestsPerSlot: 3,
};
