/**
 * Seed / mock data used until the Centre Management API is live.
 * The useCentres hook falls back to this when the endpoints are unavailable.
 */
import { PLAN_COLORS } from './constants';

import type { CentreBooking, CentreMember, CentreWithKPI, PlanBreakdownItem } from './types';

const breakdown = (p: Record<string, number>): PlanBreakdownItem[] => [
  { planId: 'premium', label: 'Premium', colour: PLAN_COLORS.premium, members: p.P },
  { planId: 'standard', label: 'Standard', colour: PLAN_COLORS.standard, members: p.S },
  { planId: 'family', label: 'Family', colour: PLAN_COLORS.family, members: p.F },
  { planId: 'offpeak', label: 'Off Peak', colour: PLAN_COLORS.offpeak, members: p.OP },
  { planId: 'nightowl', label: 'Night Owl', colour: PLAN_COLORS.nightowl, members: p.NO },
];

const stdHours = (open: string, close: string) =>
  Array.from({ length: 7 }, (_, day) => ({ day, openTime: open, closeTime: close, isOpen: true }));

export const SEED_CENTRES: CentreWithKPI[] = [
  {
    id: 'hou',
    name: 'Houston',
    shortCode: 'HOU001',
    status: 'active',
    colour: '#21295A',
    flag: '🇺🇸',
    addressLine1: '1200 Cricket Way',
    city: 'Houston',
    state: 'TX',
    postcode: '77002',
    country: 'US',
    timezone: 'America/Chicago',
    timezoneLabel: null,
    phone: '+1 713 000 0000',
    email: 'houston@centurycricket.com',
    overallCapacity: 450,
    foundationPool: 100,
    battingLanes: 4,
    bowlingLanes: 1,
    multipurposeLanes: 1,
    slotDurationMinutes: 45,
    advanceBookingWindowDays: 7,
    is24x7: true,
    operatingHours: stdHours('00:00', '23:59'),
    kpi: {
      centreId: 'hou',
      totalMembers: 812,
      activeMembers: 744,
      utilisationPct: 78,
      noShowPct: 5.1,
      bookings30d: 3840,
      planBreakdown: breakdown({ P: 88, S: 324, F: 180, OP: 140, NO: 80 }),
    },
  },
  {
    id: 'nyc',
    name: 'New York',
    shortCode: 'NYC001',
    status: 'active',
    colour: '#008482',
    flag: '🇺🇸',
    addressLine1: '50 Wicket Ave',
    city: 'New York',
    state: 'NY',
    postcode: '10001',
    country: 'US',
    timezone: 'America/New_York',
    timezoneLabel: null,
    phone: '+1 212 000 0000',
    email: 'newyork@centurycricket.com',
    overallCapacity: 450,
    foundationPool: 120,
    battingLanes: 5,
    bowlingLanes: 2,
    multipurposeLanes: 1,
    slotDurationMinutes: 45,
    advanceBookingWindowDays: 7,
    is24x7: true,
    operatingHours: stdHours('00:00', '23:59'),
    kpi: {
      centreId: 'nyc',
      totalMembers: 968,
      activeMembers: 904,
      utilisationPct: 82,
      noShowPct: 4.6,
      bookings30d: 4480,
      planBreakdown: breakdown({ P: 112, S: 428, F: 204, OP: 124, NO: 100 }),
    },
  },
  {
    id: 'mel',
    name: 'Melbourne',
    shortCode: 'MEL001',
    status: 'active',
    colour: '#7c3aed',
    flag: '🇦🇺',
    addressLine1: '88 Boundary Rd',
    city: 'Melbourne',
    state: 'VIC',
    postcode: '3000',
    country: 'AU',
    timezone: 'Australia/Melbourne',
    timezoneLabel: 'AEST',
    phone: '+61 3 0000 0000',
    email: 'melbourne@centurycricket.com',
    overallCapacity: 450,
    foundationPool: 110,
    battingLanes: 4,
    bowlingLanes: 1,
    multipurposeLanes: 2,
    slotDurationMinutes: 45,
    advanceBookingWindowDays: 7,
    is24x7: false,
    operatingHours: [
      ...stdHours('06:00', '23:00').slice(0, 5),
      { day: 5, openTime: '08:00', closeTime: '20:00', isOpen: true },
      { day: 6, openTime: '08:00', closeTime: '20:00', isOpen: true },
    ],
    kpi: {
      centreId: 'mel',
      totalMembers: 876,
      activeMembers: 802,
      utilisationPct: 80,
      noShowPct: 6.2,
      bookings30d: 3920,
      planBreakdown: breakdown({ P: 102, S: 384, F: 168, OP: 122, NO: 100 }),
    },
  },
  {
    id: 'njy',
    name: 'New Jersey',
    shortCode: 'NJY001',
    status: 'active',
    colour: '#d97706',
    flag: '🇺🇸',
    addressLine1: '14 Pitch Lane',
    city: 'Newark',
    state: 'NJ',
    postcode: '07102',
    country: 'US',
    timezone: 'America/New_York',
    timezoneLabel: null,
    phone: '+1 973 000 0000',
    email: 'newjersey@centurycricket.com',
    overallCapacity: 360,
    foundationPool: 80,
    battingLanes: 3,
    bowlingLanes: 1,
    multipurposeLanes: 1,
    slotDurationMinutes: 45,
    advanceBookingWindowDays: 7,
    is24x7: true,
    operatingHours: stdHours('00:00', '23:59'),
    kpi: {
      centreId: 'njy',
      totalMembers: 540,
      activeMembers: 488,
      utilisationPct: 64,
      noShowPct: 7.1,
      bookings30d: 2260,
      planBreakdown: breakdown({ P: 58, S: 228, F: 112, OP: 82, NO: 60 }),
    },
  },
  {
    id: 'blr',
    name: 'Bangalore',
    shortCode: 'BLR001',
    status: 'active',
    colour: '#0891b2',
    flag: '🇮🇳',
    addressLine1: '21 MG Road',
    city: 'Bangalore',
    state: 'Karnataka',
    postcode: '560001',
    country: 'IN',
    timezone: 'Asia/Kolkata',
    timezoneLabel: 'IST',
    phone: '+91 80 0000 0000',
    email: 'bangalore@centurycricket.com',
    overallCapacity: 360,
    foundationPool: 90,
    battingLanes: 4,
    bowlingLanes: 1,
    multipurposeLanes: 1,
    slotDurationMinutes: 45,
    advanceBookingWindowDays: 7,
    is24x7: false,
    operatingHours: stdHours('06:00', '23:00'),
    kpi: {
      centreId: 'blr',
      totalMembers: 624,
      activeMembers: 571,
      utilisationPct: 72,
      noShowPct: 5.8,
      bookings30d: 2740,
      planBreakdown: breakdown({ P: 68, S: 264, F: 136, OP: 96, NO: 60 }),
    },
  },
];

const PLAN_POOL = ['Premium', 'Standard', 'Family', 'Off Peak', 'Night Owl'];
const STATUS_POOL: CentreMember['status'][] = [
  'Active',
  'Active',
  'Active',
  'On Hold',
  'Active',
  'Suspended',
  'Active',
  'Active',
];
const TYPE_POOL = ['Adult', 'Adult', 'Family', 'Junior', 'Adult', 'Adult', 'Family', 'Adult'];
const MEMBER_NAMES = [
  'James Patel',
  'Sarah Mitchell',
  'Daniel Chen',
  'Oliver Kwame',
  'Emily Torres',
  'Raj Sharma',
  'Grace Williams',
  "Liam O'Brien",
];

export const seedMembers = (centreId: string): CentreMember[] =>
  MEMBER_NAMES.map((name, i) => ({
    id: `${centreId.toUpperCase()}-M${101 + i}`,
    name,
    email: `${name.toLowerCase().replace(/[^a-z]/g, '.')}@email.com`,
    plan: PLAN_POOL[i % PLAN_POOL.length],
    memberType: TYPE_POOL[i],
    joinDate: `Mar ${10 + i}, 2025`,
    bookings: ((i * 7 + 5) % 20) + 5,
    status: STATUS_POOL[i],
  }));

const LANES = ['Batting 1', 'Batting 2', 'Bowling 1', 'Multi-purpose 1', 'Batting 3'];
const SESSION_TYPES = ['Batting Practice', 'Bowling', 'Coaching', 'Open Net', 'Match Sim'];
const BOOKING_STATUS: CentreBooking['status'][] = [
  'Confirmed',
  'Completed',
  'No-show',
  'Confirmed',
  'Waitlisted',
  'Cancelled',
  'Completed',
  'Confirmed',
];

export const seedBookings = (centreId: string): CentreBooking[] =>
  Array.from({ length: 8 }, (_, i) => ({
    id: `${centreId.toUpperCase()}-B${2001 + i}`,
    member: MEMBER_NAMES[i % MEMBER_NAMES.length],
    lane: LANES[i % LANES.length],
    date: `Jun ${1 + i}, 2026`,
    time: `${(8 + i) % 24}:00 – ${(9 + i) % 24}:00`,
    sessionType: SESSION_TYPES[i % SESSION_TYPES.length],
    status: BOOKING_STATUS[i],
  }));
